# Generated by Django 3.2.9 on 2021-12-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='contennt',
            new_name='content',
        ),
    ]
