# Generated by Django 3.2.9 on 2021-12-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_contennt_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='subject',
            new_name='question',
        ),
    ]
